# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Demo"
#  url = "#hero"
#  weight = 10

[[main]]
  name = "Experience/CV"
  url = "#experience"
  weight = 10

#[[main]]
# name = "Skills"
# url = "#skills"
#  weight = 5

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
#[[main]]
#   name = "CV(short)"
#   url = "files/cv_short_1.pdf"
#   weight = 15

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 20

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 30

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 40

#[[main]]
#  name = "Courses"
#  url = "courses/"
 # weight = 50

[[main]]
  name = "Accomplishments"
  url = "#accomplishments"
  weight = 60

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 65

[[main]]
  name = "Gallery"
  url = "#projects"
  weight = 71

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80


